global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System;
global using SunamoValues;
global using SunamoEnums.Enums;
global using SunamoChar.Enums;
global using SunamoExceptions.OnlyInSE;
global using SunamoValues.Values;
